### ISSUE TITLE
bananapi m2 zero

### ISSUE THREAD

**Issue by raserdk** [Berny23/LD-ToyPad-Emulator#110]
the usb setup script errors out  on 
mkdir functions/hid.g0
echo 32 > functions/hid.g0/report_length
echo -ne "\x06\x00\xFF\x09\x01\xA1\x01\x19\x01\x29\x20\x15\x00\x26\xFF\x00\x75\x08\x95\x20\x81\x00\x19\x01\x29\x20\x91\x00\xC0" > functions/hid.g0/report_desc
and says device or resource is busy

and in dev there is no device called hidg0 or hid.g0

Error: ENOENT: no such file or directory, open '/dev/hidg0'
    at Object.openSync (fs.js:448:3)
    at new RawTransport (/root/LD-ToyPad-Emulator/node_modules/node-ld/dist/transports/raw.js:11:27)
    at new ToyPadEmu (/root/LD-ToyPad-Emulator/node_modules/node-ld/dist/lib/ToyPadEmu.js:65:69)
    at Object.<anonymous> (/root/LD-ToyPad-Emulator/index.js:24:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
root@bananapim2zero:~/LD-ToyPad-Emulator#

**Comment by raserdk** [comment]
you know what after hours of hours and so many images for the banana pi m2 zero i finally found an image that worked with this

[](https://github.com/armbian/community/releases/download/202307/Armbian_23.02.0-trunk_Bananapi_lunar_edge_6.1.11.img.xz#bananapi`)


this works
