### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/dev/hidg0'

### ISSUE THREAD

**Issue by doritobob269** [Berny23/LD-ToyPad-Emulator#144]
Hello,

I followed the [Option 2: Single Board Computer](https://github.com/Berny23/LD-ToyPad-Emulator#option-2-single-board-computer) instructions for how to set this up on a raspberry pi zero w with the intention to use it on real wiiu hardware to play Lego Dimesions. I am running raspberry pi os lite 32-bit and when I got to the instruction `node index.js`, I get the following error. What do I need to do to fix this error? If there is any other information you need me to include, please let me know.

```
doritobob@raspberrypi:~/LD-ToyPad-Emulator $ node index.js
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/dev/hidg0'
    at Object.openSync (fs.js:448:3)
    at new RawTransport (/home/doritobob/LD-ToyPad-Emulator/node_modules/node-ld/dist/transports/raw.js:11:27)
    at new ToyPadEmu (/home/doritobob/LD-ToyPad-Emulator/node_modules/node-ld/dist/lib/ToyPadEmu.js:65:69)
    at Object.<anonymous> (/home/doritobob/LD-ToyPad-Emulator/index.js:24:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load `(internal/modules/cjs/loader.js:685:32)`
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by doritobob269** [comment]
I got this working. The key is you need to make sure you have 
dtoverlay=dwc2,dr_mode=peripheral 
at the end of config.txt
modules-load=dwc2,g_hid
at the end of cmdline.txt

I had my cmdline.txt setup for ethernet connection instead of usb gadget

**Comment by doritobob269** [comment]
I got this working. The key is you need to make sure you have
dtoverlay=dwc2,dr_mode=peripheral
at the end of config.txt
modules-load=dwc2,g_hid
at the end of cmdline.txt

I had my cmdline.txt setup for ethernet connection instead of usb gadget
