### ISSUE TITLE
node index.js

### ISSUE THREAD

**Issue by capper742** [Berny23/LD-ToyPad-Emulator#167]
Have been working for 2 months with no issues.

Yesterday when I went to launch the ToyPad and I got to entering the node index.js step, and i got the below error.

Any ideas?
-----------------------------------------------------
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at initalizeToyTagsJSON (/home/capper742/LD-ToyPad-Emulator/index.js:140:25)
    at Object.<anonymous> (/home/capper742/LD-ToyPad-Emulator/index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

**Comment by Vihu360** [comment]
The error is occurring in the initializeToyTagsJSON function at line 140 of your index.js file.

Have you tried error handling in the function ? if not, here i am giving the template, try it you will get more clarity about your errors. 

try {
    // Your code
} catch (error) {
    console.error('Error :', error);
}
