### ISSUE TITLE
node index.js step returns syntax error

### ISSUE THREAD

**Issue by Georgedude** [Berny23/LD-ToyPad-Emulator#170]
george@debian:~/LD-ToyPad-Emulator$ node index.js
undefined:11
]5": 4026531839
 ^

SyntaxError: Unexpected number in JSON at position 208
    at JSON.parse (<anonymous>)
    at initalizeToyTagsJSON (/home/george/LD-ToyPad-Emulator/index.js:140:25)
    at Object.<anonymous> (/home/george/LD-ToyPad-Emulator/index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

Any ideas what I can do to solve this? I've had a look in the index.js file for the mentioned ]5" with ctrlF but no luck, but I'm also not knowledgeable on the topic so I'm sure I'm misunderstanding something

**Comment by casioforever** [comment]
I just Deleted The Whole Game, Worst Experience Ever.
