### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/dev/hidg0'

### ISSUE THREAD

**Issue by GlitcherFN** [Berny23/LD-ToyPad-Emulator#53]
![image](https://user-images.githubusercontent.com/61569905/154545473-b3cd7dc6-4c34-434c-aadc-6ee095057ae1.png)
F:\LD-ToyPad-Emulator>node index.js
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/dev/hidg0'
    at Object.openSync (node:fs:585:3)
    at new RawTransport (F:\LD-ToyPad-Emulator\node_modules\node-ld\dist\transports\raw.js:11:27)
    at new ToyPadEmu (F:\LD-ToyPad-Emulator\node_modules\node-ld\dist\lib\ToyPadEmu.js:65:69)
    at Object.<anonymous> (F:\LD-ToyPad-Emulator\index.js:24:10)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '/dev/hidg0'
}

**Comment by GlitcherFN** [comment]
nvm fixed it by redoing the whole process
