### ISSUE TITLE
Raspberri PI zero W does not recognize the game 

### ISSUE THREAD

**Issue by ignacioat2** [Berny23/LD-ToyPad-Emulator#77]
I have a problem. All the programming is fine (thats what i think) even it tells me tags are synced but it seems that both the raspberry and the PC/PS4 do not recognize each other. I also get this when trying to place a character in the toypad emulator: Server running on port 80
<<Syncing tags, one moment...>>
<<Tags are synced!>>
<<<Syncing tags, one moment...>>
<<Tags are synced!>>
Placing tag: 38
Character tag: 38
Planning to set UID: 04F2D623CCB080 to index 2
(node:7354) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
EVENT: Event { pad: '1', index: '2', dir: 0, uid: '04F2D623CCB080' }
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: ESHUTDOWN: cannot send after transport endpoint shutdown, write
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at fs.write (internal/fs/streams.js:307:14)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:525:5)
Server running on port 80
<<Syncing tags, one moment...>>
<<Tags are synced!>>
<<<Syncing tags, one moment...>>
<<Tags are synced!>>
Placing tag: 38
Character tag: 38
Planning to set UID: 04F2D623CCB080 to index 2
(node:7354) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
EVENT: Event { pad: '1', index: '2', dir: 0, uid: '04F2D623CCB080' }
events.js:170
      throw er; // Unhandled 'error' event
      ^

Error: ESHUTDOWN: cannot send after transport endpoint shutdown, write
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at fs.write (internal/fs/streams.js:307:14)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:525:5)

Also it says before this: npm WARN ws@8.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

**Comment by ignacioat2** [comment]
i got it working it was a cable problem if you have this same problem probably it would mean that your cable cant transmit data.
